name: macOS Web Terminal (ttyd + Cloudflare Tunnel, fixed input)
on:
  workflow_dispatch: {}

jobs:
  mac_web_term:
    runs-on: macos-15
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v4

      - name: Install ttyd & cloudflared
        run: |
          brew update
          brew install ttyd cloudflared

      - name: Launch web terminal with login shell
        shell: bash
        run: |
          nohup ttyd --check-origin=false -p 7681 login -fp $(whoami) > /tmp/ttyd.log 2>&1 &
          nohup cloudflared tunnel --url http://localhost:7681 --no-autoupdate > /tmp/cloudflared.log 2>&1 &

          for i in {1..60}; do
            URL=$(grep -oE 'https://[a-zA-Z0-9.-]+trycloudflare.com' /tmp/cloudflared.log | head -n1 || true)
            if [[ -n "$URL" ]]; then
              echo "### Web terminal" >> "$GITHUB_STEP_SUMMARY"
              echo "$URL" >> "$GITHUB_STEP_SUMMARY"
              echo "::notice title=Web terminal::$URL"
              break
            fi
            sleep 2
          done

          tail -f /dev/null
