name: macOS Web Terminal (ttyd + Cloudflare Tunnel) gpt
on:
  workflow_dispatch: {}

jobs:
  mac_web_term:
    runs-on: macos-15
    timeout-minutes: 180
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install ttyd & cloudflared
        run: |
          brew update
          brew install ttyd cloudflared

      - name: Launch web terminal and expose it
        shell: bash
        run: |
          # 1) Web terminali başlat (ttyd, zsh kabuğu)
          nohup ttyd -p 7681 /bin/zsh > /tmp/ttyd.log 2>&1 &

          # 2) Cloudflare Quick Tunnel ile herkese açık URL oluştur
          nohup cloudflared tunnel --url http://localhost:7681 --no-autoupdate > /tmp/cloudflared.log 2>&1 &

          # 3) URL'yi logdan çek ve Summary'ye yaz
          for i in {1..60}; do
            URL=$(grep -oE 'https://[a-zA-Z0-9.-]+trycloudflare.com' /tmp/cloudflared.log | head -n1 || true)
            if [[ -n "$URL" ]]; then
              echo "### Web terminal" >> "$GITHUB_STEP_SUMMARY"
              echo "$URL" >> "$GITHUB_STEP_SUMMARY"
              echo "::notice title=Web terminal::$URL"
              break
            fi
            sleep 2
          done

          # 4) Job'ı canlı tut (terminal açık kalsın)
          tail -f /dev/null
