name: macOS Web Terminal (tmate) Gpt

on:
  workflow_dispatch: {}

concurrency:
  group: mac-web-terminal
  cancel-in-progress: true

jobs:
  open_web_terminal:
    # macos-15 GA; 'macos-latest' etiketi 4 Ağu–1 Eyl 2025'te 15'e taşınıyor.
    runs-on: macos-15
    timeout-minutes: 180
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # tmate: SSH + Web terminal linki üretir
      - name: Start tmate session (public web link)
        id: tmate
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          # Linke sahip herkes bağlansın (şifre/anahtar kısıtı yok)
          limit-access-to-actor: false

      # Tıklanabilir özet
      - name: Publish connection links
        if: ${{ always() }}
        run: |
          echo "### tmate bağlantıları" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- **Web terminal**: ${{ steps.tmate.outputs.web-url }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- **SSH (istersen)**: \`${{ steps.tmate.outputs.ssh-command }}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "> Oturum, job süresi/timeout bitene kadar açık." >> "$GITHUB_STEP_SUMMARY"
